import { Montserrat } from "next/font/google"
import "./globals.css";


const MontserratFont = Montserrat({
  subsets: ['latin'],
  style: ['normal', 'italic'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-Montserrat',
  display: 'swap',
})

export const metadata = {
  title: "My Hostel",
  description: "Generated by Bhumik jain",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className={` ${MontserratFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
